services:
  - type: web
    name: trustpay-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SUPABASE_URL
        fromEnvVar: SUPABASE_URL
      - key: SUPABASE_KEY
        fromEnvVar: SUPABASE_KEY
